#!/bin/sh
go generate github.com/apesternikov/backplane/...
go install github.com/apesternikov/backplane/src/config/...
#go get github.com/apesternikov/bindata/mkbinfs/
mkbinfs src/backplane/static/
go install github.com/apesternikov/backplane/src/backplane/static/...