// Code generated by protoc-gen-go.
// source: swim.proto
// DO NOT EDIT!

/*
Package swim is a generated protocol buffer package.

It is generated from these files:
	swim.proto

It has these top-level messages:
	Ping
	Ack
	PingReq
	SwimMessage
*/
package swim

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Ping struct {
	SourceNode string `protobuf:"bytes,1,opt,name=source_node" json:"source_node,omitempty"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}

type Ack struct {
	Alive bool `protobuf:"varint,1,opt,name=alive" json:"alive,omitempty"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}

// request to remote ping
type PingReq struct {
	SourceNode string `protobuf:"bytes,1,opt,name=source_node" json:"source_node,omitempty"`
	DestNode   string `protobuf:"bytes,2,opt,name=dest_node" json:"dest_node,omitempty"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}

type SwimMessage struct {
	Seq int64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	// one of the following
	Ping    *Ping    `protobuf:"bytes,2,opt,name=ping" json:"ping,omitempty"`
	Ack     *Ack     `protobuf:"bytes,3,opt,name=ack" json:"ack,omitempty"`
	PingReq *PingReq `protobuf:"bytes,4,opt,name=ping_req" json:"ping_req,omitempty"`
}

func (m *SwimMessage) Reset()         { *m = SwimMessage{} }
func (m *SwimMessage) String() string { return proto.CompactTextString(m) }
func (*SwimMessage) ProtoMessage()    {}

func (m *SwimMessage) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *SwimMessage) GetAck() *Ack {
	if m != nil {
		return m.Ack
	}
	return nil
}

func (m *SwimMessage) GetPingReq() *PingReq {
	if m != nil {
		return m.PingReq
	}
	return nil
}

func init() {
}
