// Code generated by protoc-gen-go.
// source: requestlog.proto
// DO NOT EDIT!

/*
Package requestlog is a generated protocol buffer package.

It is generated from these files:
	requestlog.proto

It has these top-level messages:
	Item
*/
package requestlog

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// HTTP request log
type Item struct {
	ClientIp          string `protobuf:"bytes,1,opt,name=client_ip" json:"client_ip,omitempty"`
	TimeTNs           int64  `protobuf:"varint,2,opt,name=time_t_ns" json:"time_t_ns,omitempty"`
	Method            string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	RequestUri        string `protobuf:"bytes,4,opt,name=request_uri" json:"request_uri,omitempty"`
	HttpVersion       string `protobuf:"bytes,5,opt,name=http_version" json:"http_version,omitempty"`
	StatusCode        int64  `protobuf:"varint,6,opt,name=status_code" json:"status_code,omitempty"`
	ResponseSize      int64  `protobuf:"varint,7,opt,name=response_size" json:"response_size,omitempty"`
	Referrer          string `protobuf:"bytes,8,opt,name=referrer" json:"referrer,omitempty"`
	UserAgent         string `protobuf:"bytes,9,opt,name=user_agent" json:"user_agent,omitempty"`
	Frontend          string `protobuf:"bytes,10,opt,name=frontend" json:"frontend,omitempty"`
	IsTls             bool   `protobuf:"varint,11,opt,name=is_tls" json:"is_tls,omitempty"`
	Vhost             string `protobuf:"bytes,12,opt,name=vhost" json:"vhost,omitempty"`
	HandlerPath       string `protobuf:"bytes,13,opt,name=handler_path" json:"handler_path,omitempty"`
	BackendName       string `protobuf:"bytes,14,opt,name=backend_name" json:"backend_name,omitempty"`
	ServerAddress     string `protobuf:"bytes,15,opt,name=server_address" json:"server_address,omitempty"`
	FrontendLatencyNs int64  `protobuf:"varint,100,opt,name=frontend_latency_ns" json:"frontend_latency_ns,omitempty"`
	ServerLatencyNs   int64  `protobuf:"varint,101,opt,name=server_latency_ns" json:"server_latency_ns,omitempty"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func init() {
}
